FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install 
COPY . .

expose 3000
CMD ["npm", "run", "start"]


#FROM nginx:alpine
#COPY nginx.conf /etc/nginx/conf.d/default.conf
#COPY --from=builder /app/dist /usr/share/nginx/html/vendingmachine
