# Blockfrost and IPFS keys
blockfrost.api.key=${BLOCKFROST_API_KEY}
ipfs.api.key=${IPFS_API_KEY}
recovery.phrase=${RECOVERY_PHRASE}}

blockfrost.api.url=https://cardano-mainnet.blockfrost.io/api/v0
ipfs.api.url=https://ipfs.blockfrost.io/api/v0/

network.id=1
network.magic=764824073